#!/bin/python3
import os
from tkinter import ttk
from tkinter import *
from tkinter.filedialog import askopenfilename, askdirectory

window=Tk()
window.resizable=True
window.title("Samba network folder add")
window.geometry('400x400+700+200')
mountdir=""
def choosedir():
    global mountdir
    mountdir=askdirectory()
    

def mount():
    ipv=ip.get()
    namev=name.get()
    usernamev=username.get()
    passwv=passw.get()
    command=f"pkexec mount -t cifs -o username={usernamev},password={passwv} //{ipv}/{namev} {mountdir}"
    os.system(command)
    file=open("fstab.txt", "w")
    file.write("asdf\n")
    file.close()
    os.system("cat /etc/fstab > fstab.txt")
    file2=open("fstab.txt", "r")
    fstabtext=file2.read()
    if fstabtext.find(f"{usernamev}@{ipv}:{namev} {mountdir} cifs username={usernamev},password={passwv} 0 0")==-1:
        command2=f'echo "{usernamev}@{ipv}:{namev} {mountdir} cifs username={usernamev},password={passwv} 0 0" | pkexec tee /etc/fstab > /dev/null'
        os.system(command2)
    else:
        warn = Toplevel(window)
        warn.geometry("200x200+900+400")
        warn.title("Already in automount")
        wl=Label(text="Folder already in /etc/fstab (already automounting)")

ip=Entry()
name=Entry()
username=Entry()
passw=Entry()

ipl=Label(text="Enter netpath IP")
namel=Label(text="Enter netpath name")
usernamel=Label(text="Enter your netpath username")
passwl=Label(text="Enter your netpath password")

choosemountpoint=Button(text="Choose mountpoint", command=choosedir)
mount=Button(text="Mount netfolder", command=mount)

ip.place(relx=0.0, rely=0.05)
name.place(relx=0.0, rely=0.15)
username.place(relx=0.0, rely=0.25)
passw.place(relx=0.0, rely=0.35)

ipl.place(relx=0.0, rely=0.0)
namel.place(relx=0.0, rely=0.1)
usernamel.place(relx=0.0, rely=0.2)
passwl.place(relx=0.0, rely=0.3)

choosemountpoint.place(relx=0.0, rely=0.55)
mount.place(relx=0.0, rely=0.45)



window.mainloop()